### ISSUE TITLE
Pull fails because `source-tag` is translated into `--branch`

### ISSUE THREAD

**Issue by sed-i** [snapcore/snapcraft#4513]
### Bug Description

Trying to pull code from a github repo specifying `source-tag` fails because it is translated into `--branch`, which doesn't exist:

```
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:32.782 :: fatal: Remote branch 0.24.0 not found in upstream origin
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:32.786 Failed to pull source: command ['git', 'clone', '--recursive', '--branch', '0.24.0', 'https://github.com/extrawurst/gitui.git', '/root/parts/gitui/src'] exited with code 128.
```

### To Reproduce

Run `snapcraft` on the provided `snapcraft.yaml` below.

### Environment

snapcraft 8.0.1 on Ubuntu 22.04.3 on multipass.

### snapcraft.yaml

```shell
name: gitui
version: '0.24.0'
summary: TODO
description: |
  TODO

confinement: devmode
base: core22

parts:
  gitui:
    plugin: rust
    source: https://github.com/extrawurst/gitui.git
    source-tag: 0.24.0

apps:
  gitui:
    command: bin/gitui
```

### Relevant log output

```shell
2024-01-08 18:57:19.648 Starting Snapcraft 8.0.1
2024-01-08 18:57:19.649 lifecycle command: 'pack', arguments: Namespace(destructive_mode=False, use_lxd=False, debug=False, enable_manifest=False, manifest_image_information=None, bind_ssh=False, build_for=None, http_proxy=None, https_proxy=None, ua_token=None, enable_experimental_ua_services=False, enable_experimental_plugins=False, enable_experimental_extensions=False, enable_developer_debug=False, enable_experimental_target_arch=False, target_arch=None, provider=None, directory=None, output=None)
2024-01-08 18:57:19.649 command: pack, arguments: Namespace(destructive_mode=False, use_lxd=False, debug=False, enable_manifest=False, manifest_image_information=None, bind_ssh=False, build_for=None, http_proxy=None, https_proxy=None, ua_token=None, enable_experimental_ua_services=False, enable_experimental_plugins=False, enable_experimental_extensions=False, enable_developer_debug=False, enable_experimental_target_arch=False, target_arch=None, provider=None, directory=None, output=None)
2024-01-08 18:57:19.654 CPU count (from process affinity): 2
2024-01-08 18:57:19.654 Invalid SNAPCRAFT_MAX_PARALLEL_BUILD_COUNT ''
2024-01-08 18:57:19.654 Running on amd64 for amd64
2024-01-08 18:57:19.655 Checking build provider availability
2024-01-08 18:57:19.675 Retrieved snap config: {}
2024-01-08 18:57:19.675 Using default provider 'lxd' on linux system.
2024-01-08 18:57:19.840 Executing on host: lxc --project default profile show local:default
2024-01-08 18:57:20.092 Using hostname 'snapcraft-gitui-on-amd64-for-amd64-862'
2024-01-08 18:57:20.092 Launching instance...
2024-01-08 18:57:20.092 Executing on host: lxc remote list --format=yaml
2024-01-08 18:57:20.128 Remote 'craft-com.ubuntu.cloud-buildd' already exists.
2024-01-08 18:57:20.128 Executing on host: lxc project list local: --format=yaml
2024-01-08 18:57:20.161 Set LXD instance name to 'snapcraft-gitui-on-amd64-for-amd64-862'
2024-01-08 18:57:20.161 Checking for instance 'snapcraft-gitui-on-amd64-for-amd64-862' in project 'snapcraft' in remote 'local'
2024-01-08 18:57:20.161 Executing on host: lxc --project snapcraft list local: --format=yaml
2024-01-08 18:57:20.290 Executing on host: lxc --project snapcraft config get local:snapcraft-gitui-on-amd64-for-amd64-862 raw.idmap
2024-01-08 18:57:20.321 Executing on host: lxc --project snapcraft list local: --format=yaml
2024-01-08 18:57:20.365 Instance exists and is not running. Starting instance.
2024-01-08 18:57:20.365 Starting instance
2024-01-08 18:57:20.365 Executing on host: lxc --project snapcraft start local:snapcraft-gitui-on-amd64-for-amd64-862
2024-01-08 18:57:20.634 Executing in container: lxc --project snapcraft exec local:snapcraft-gitui-on-amd64-for-amd64-862 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin SNAPCRAFT_MANAGED_MODE=1 test -f /etc/craft-instance.conf
2024-01-08 18:57:20.955 Executing on host: lxc --project snapcraft file pull local:snapcraft-gitui-on-amd64-for-amd64-862/etc/craft-instance.conf /home/ubuntu/tmpgq1pdzkq.tmp-craft/tmppws140s8
2024-01-08 18:57:21.103 Instance has already been setup.
2024-01-08 18:57:21.104 Executing in container: lxc --project snapcraft exec local:snapcraft-gitui-on-amd64-for-amd64-862 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin SNAPCRAFT_MANAGED_MODE=1 cat /etc/os-release
2024-01-08 18:57:21.446 Executing in container: lxc --project snapcraft exec local:snapcraft-gitui-on-amd64-for-amd64-862 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin SNAPCRAFT_MANAGED_MODE=1 test -f /etc/craft-instance.conf
2024-01-08 18:57:21.661 Executing on host: lxc --project snapcraft file pull local:snapcraft-gitui-on-amd64-for-amd64-862/etc/craft-instance.conf /home/ubuntu/tmpm6jbk3yp.tmp-craft/tmpffzt3pkq
2024-01-08 18:57:21.716 Instance is compatible with compatibility tag 'snapcraft-buildd-base-v4.0'
2024-01-08 18:57:21.716 No cache path set, not mounting cache directories.
2024-01-08 18:57:21.716 Waiting for environment to be ready...
2024-01-08 18:57:21.716 Executing in container: lxc --project snapcraft exec local:snapcraft-gitui-on-amd64-for-amd64-862 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin SNAPCRAFT_MANAGED_MODE=1 systemctl is-system-running
2024-01-08 18:57:21.815 systemctl is-system-running status: starting
2024-01-08 18:57:22.065 Executing in container: lxc --project snapcraft exec local:snapcraft-gitui-on-amd64-for-amd64-862 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin SNAPCRAFT_MANAGED_MODE=1 systemctl is-system-running
2024-01-08 18:57:22.288 systemctl is-system-running status: starting
2024-01-08 18:57:22.539 Executing in container: lxc --project snapcraft exec local:snapcraft-gitui-on-amd64-for-amd64-862 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin SNAPCRAFT_MANAGED_MODE=1 systemctl is-system-running
2024-01-08 18:57:22.780 systemctl is-system-running status: starting
2024-01-08 18:57:23.030 Executing in container: lxc --project snapcraft exec local:snapcraft-gitui-on-amd64-for-amd64-862 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin SNAPCRAFT_MANAGED_MODE=1 systemctl is-system-running
2024-01-08 18:57:23.165 Waiting for networking to be ready...
2024-01-08 18:57:23.165 Executing in container: lxc --project snapcraft exec local:snapcraft-gitui-on-amd64-for-amd64-862 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin SNAPCRAFT_MANAGED_MODE=1 getent hosts snapcraft.io
2024-01-08 18:57:23.291 Executing in container: lxc --project snapcraft exec local:snapcraft-gitui-on-amd64-for-amd64-862 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin SNAPCRAFT_MANAGED_MODE=1 snap unset system proxy.http
2024-01-08 18:57:23.536 Executing in container: lxc --project snapcraft exec local:snapcraft-gitui-on-amd64-for-amd64-862 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin SNAPCRAFT_MANAGED_MODE=1 snap unset system proxy.https
2024-01-08 18:57:23.827 Installing snap 'snapcraft' with channel=None and classic=True
2024-01-08 18:57:23.827 Installing snap 'snapcraft' from host (classic=True)
2024-01-08 18:57:23.836 Installing base snap 'core22' for 'snapcraft' from host
2024-01-08 18:57:23.836 Installing snap 'core22' from host (classic=False)
2024-01-08 18:57:23.837 Executing in container: lxc --project snapcraft exec local:snapcraft-gitui-on-amd64-for-amd64-862 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin SNAPCRAFT_MANAGED_MODE=1 test -f /etc/craft-instance.conf
2024-01-08 18:57:24.001 Executing on host: lxc --project snapcraft file pull local:snapcraft-gitui-on-amd64-for-amd64-862/etc/craft-instance.conf /home/ubuntu/tmpax9ale3t.tmp-craft/tmpj3i2etdw
2024-01-08 18:57:24.037 Revisions found: host='1033', target='1033'
2024-01-08 18:57:24.037 Skipping snap injection: target is already up-to-date with revision on host
2024-01-08 18:57:24.037 Executing in container: lxc --project snapcraft exec local:snapcraft-gitui-on-amd64-for-amd64-862 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin SNAPCRAFT_MANAGED_MODE=1 test -f /etc/craft-instance.conf
2024-01-08 18:57:24.151 Executing on host: lxc --project snapcraft file pull local:snapcraft-gitui-on-amd64-for-amd64-862/etc/craft-instance.conf /home/ubuntu/tmpntftlc44.tmp-craft/tmp6bllfyvs
2024-01-08 18:57:24.189 Revisions found: host='10279', target='10279'
2024-01-08 18:57:24.189 Skipping snap injection: target is already up-to-date with revision on host
2024-01-08 18:57:24.189 Executing on host: lxc --project snapcraft config device show local:snapcraft-gitui-on-amd64-for-amd64-862
2024-01-08 18:57:24.224 Executing on host: lxc --project snapcraft config device add local:snapcraft-gitui-on-amd64-for-amd64-862 disk-/root/project disk source=/home/ubuntu/code/personal-development/gitui-snap path=/root/project
2024-01-08 18:57:24.282 Executing on host: lxc --project snapcraft file push /tmp/tmpstu3fkpb local:snapcraft-gitui-on-amd64-for-amd64-862/root/.bashrc --mode=644
2024-01-08 18:57:24.315 Executing in container: lxc --project snapcraft exec local:snapcraft-gitui-on-amd64-for-amd64-862 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin SNAPCRAFT_MANAGED_MODE=1 chown root:root /root/.bashrc
2024-01-08 18:57:24.368 Emitter: Pausing control of the terminal
2024-01-08 18:57:33.190 Emitter: Resuming control of the terminal
2024-01-08 18:57:33.190 Executing in container: lxc --project snapcraft exec local:snapcraft-gitui-on-amd64-for-amd64-862 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin SNAPCRAFT_MANAGED_MODE=1 test -f /tmp/snapcraft.log
2024-01-08 18:57:33.456 Executing on host: lxc --project snapcraft file pull local:snapcraft-gitui-on-amd64-for-amd64-862/tmp/snapcraft.log /home/ubuntu/tmpveuk_4qs.tmp-craft/tmpaanbap0r
2024-01-08 18:57:33.518 Logs retrieved from managed instance:
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:27.924 Starting Snapcraft 8.0.1
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:27.925 lifecycle command: 'pack', arguments: Namespace(destructive_mode=False, use_lxd=False, debug=False, enable_manifest=False, manifest_image_information=None, bind_ssh=False, build_for='amd64', http_proxy=None, https_proxy=None, ua_token=None, enable_experimental_ua_services=False, enable_experimental_plugins=False, enable_experimental_extensions=False, enable_developer_debug=False, enable_experimental_target_arch=False, target_arch=None, provider=None, directory=None, output=None)
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:27.925 command: pack, arguments: Namespace(destructive_mode=False, use_lxd=False, debug=False, enable_manifest=False, manifest_image_information=None, bind_ssh=False, build_for='amd64', http_proxy=None, https_proxy=None, ua_token=None, enable_experimental_ua_services=False, enable_experimental_plugins=False, enable_experimental_extensions=False, enable_developer_debug=False, enable_experimental_target_arch=False, target_arch=None, provider=None, directory=None, output=None)
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:27.931 CPU count (from process affinity): 2
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:27.931 Invalid SNAPCRAFT_MAX_PARALLEL_BUILD_COUNT ''
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:27.931 Running on amd64 for amd64
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:27.932 Initializing parts lifecycle
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:27.936 is_snap: True, SNAP_NAME set to snapcraft
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:27.936 process gitui:Step.PULL
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:27.936 add action gitui:Step.PULL(ActionType.RUN)
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:27.936 process gitui:Step.BUILD
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:27.937 add action gitui:Step.BUILD(ActionType.RUN)
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:27.937 process gitui:Step.STAGE
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:27.937 add action gitui:Step.STAGE(ActionType.RUN)
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:27.937 process gitui:Step.PRIME
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:27.937 add action gitui:Step.PRIME(ActionType.RUN)
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:27.938 source build packages: {'git'}
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:27.938 plugin build packages: {'gcc', 'curl', 'git', 'findutils', 'pkg-config'}
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:27.938 Installing build-packages
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:27.938 Requested build-packages: ['curl', 'findutils', 'gcc', 'git', 'pkg-config']
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:28.790 Marking gcc (and its dependencies) to be fetched
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:28.791 package: gcc
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:28.795 Marking findutils (and its dependencies) to be fetched
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:28.795 package: findutils
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:28.799 Marking curl (and its dependencies) to be fetched
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:28.799 package: curl
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:28.803 Marking git (and its dependencies) to be fetched
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:28.803 package: git
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:28.806 Marking pkg-config (and its dependencies) to be fetched
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:28.807 package: pkg-config
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:28.838 Executing: ['apt-get', 'update']
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:28.996 :: Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:29.023 :: Hit:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:29.053 :: Hit:3 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:29.161 :: Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:29.691 :: Reading package lists...
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:29.716 Installing packages: curl findutils gcc git pkg-config
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:29.784 :: Reading package lists...
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:29.891 :: Building dependency tree...
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:29.891 :: Reading state information...
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:29.974 :: findutils is already the newest version (4.8.0-1ubuntu3).
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:29.974 :: gcc is already the newest version (4:11.2.0-1ubuntu1).
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:29.974 :: gcc set to manually installed.
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:29.974 :: curl is already the newest version (7.81.0-1ubuntu1.15).
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:29.974 :: git is already the newest version (1:2.34.1-1ubuntu1.10).
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:29.974 :: The following additional packages will be installed:
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:29.974 :: libglib2.0-0
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:29.974 :: Recommended packages:
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:29.974 :: libglib2.0-data shared-mime-info xdg-user-dirs
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:29.986 :: The following NEW packages will be installed:
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:29.986 :: libglib2.0-0 pkg-config
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:30.078 :: 0 upgraded, 2 newly installed, 0 to remove and 79 not upgraded.
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:30.078 :: Need to get 1511 kB of archives.
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:30.078 :: After this operation, 4314 kB of additional disk space will be used.
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:30.078 :: Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libglib2.0-0 amd64 2.72.4-0ubuntu2.2 [1463 kB]
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:31.004 :: Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 pkg-config amd64 0.29.2-1ubuntu3 [48.2 kB]
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:31.226 :: Fetched 1511 kB in 1s (1443 kB/s)
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:31.275 :: Selecting previously unselected package libglib2.0-0:amd64.
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:31.279 :: (Reading database ... 17525 files and directories currently installed.)
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:31.279 :: Preparing to unpack .../libglib2.0-0_2.72.4-0ubuntu2.2_amd64.deb ...
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:31.303 :: Unpacking libglib2.0-0:amd64 (2.72.4-0ubuntu2.2) ...
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:31.411 :: Selecting previously unselected package pkg-config.
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:31.412 :: Preparing to unpack .../pkg-config_0.29.2-1ubuntu3_amd64.deb ...
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:31.416 :: Unpacking pkg-config (0.29.2-1ubuntu3) ...
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:31.486 :: Setting up libglib2.0-0:amd64 (2.72.4-0ubuntu2.2) ...
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:31.512 :: No schema files found: doing nothing.
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:31.521 :: Setting up pkg-config (0.29.2-1ubuntu3) ...
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:31.570 :: Processing triggers for libc-bin (2.35-0ubuntu3) ...
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:31.904 Found installed version 2.72.4-0ubuntu2.2 for package libglib2.0-0
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:31.904 Found installed version 0.29.2-1ubuntu3 for package pkg-config
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:31.906 Installing build-snaps
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:32.458 verify plugin environment for part 'gitui'
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:32.458 Pulling gitui
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:32.459 execute action gitui:Action(part_name='gitui', step=Step.PULL, action_type=ActionType.RUN, reason=None, project_vars=None, properties=ActionProperties(changed_files=None, changed_dirs=None))
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:32.461 Executing: git clone --recursive --branch 0.24.0 https://github.com/extrawurst/gitui.git
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:32.465 :: Cloning into '/root/parts/gitui/src'...
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:32.782 :: fatal: Remote branch 0.24.0 not found in upstream origin
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:32.786 Failed to pull source: command ['git', 'clone', '--recursive', '--branch', '0.24.0', 'https://github.com/extrawurst/gitui.git', '/root/parts/gitui/src'] exited with code 128.
2024-01-08 18:57:33.519 :: Make sure sources are correctly specified.
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:32.790 Traceback (most recent call last):
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:32.790   File "/snap/snapcraft/10279/lib/python3.10/site-packages/craft_parts/sources/base.py", line 128, in _run
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:32.790     os_utils.process_run(command, logger.debug, **kwargs)
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:32.790   File "/snap/snapcraft/10279/lib/python3.10/site-packages/craft_parts/utils/os_utils.py", line 344, in process_run
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:32.790     raise subprocess.CalledProcessError(ret, command)
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:32.790 subprocess.CalledProcessError: Command '['git', 'clone', '--recursive', '--branch', '0.24.0', 'https://github.com/extrawurst/gitui.git', '/root/parts/gitui/src']' returned non-zero exit status 128.
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:32.790
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:32.790 During handling of the above exception, another exception occurred:
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:32.790 Traceback (most recent call last):
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:32.790   File "/snap/snapcraft/10279/lib/python3.10/site-packages/snapcraft/parts/parts.py", line 190, in run
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:32.790     aex.execute(action, stdout=stream, stderr=stream)
2024-01-08 18:57:33.519 :: 2024-01-08 18:57:32.790   File "/snap/snapcraft/10279/lib/python3.10/site-packages/craft_parts/executor/executor.py", line 318, in execute
2024-01-08 18:57:33.520 :: 2024-01-08 18:57:32.790     self._executor.execute(actions, stdout=stdout, stderr=stderr)
2024-01-08 18:57:33.520 :: 2024-01-08 18:57:32.790   File "/snap/snapcraft/10279/lib/python3.10/site-packages/craft_parts/executor/executor.py", line 137, in execute
2024-01-08 18:57:33.520 :: 2024-01-08 18:57:32.790     self._run_action(act, stdout=stdout, stderr=stderr)
2024-01-08 18:57:33.520 :: 2024-01-08 18:57:32.790   File "/snap/snapcraft/10279/lib/python3.10/site-packages/craft_parts/executor/executor.py", line 205, in _run_action
2024-01-08 18:57:33.520 :: 2024-01-08 18:57:32.790     handler.run_action(action, stdout=stdout, stderr=stderr)
2024-01-08 18:57:33.520 :: 2024-01-08 18:57:32.790   File "/snap/snapcraft/10279/lib/python3.10/site-packages/craft_parts/executor/part_handler.py", line 172, in run_action
2024-01-08 18:57:33.520 :: 2024-01-08 18:57:32.790     state = handler(step_info, stdout=stdout, stderr=stderr)
2024-01-08 18:57:33.520 :: 2024-01-08 18:57:32.790   File "/snap/snapcraft/10279/lib/python3.10/site-packages/craft_parts/executor/part_handler.py", line 198, in _run_pull
2024-01-08 18:57:33.520 :: 2024-01-08 18:57:32.790     self._run_step(
2024-01-08 18:57:33.520 :: 2024-01-08 18:57:32.790   File "/snap/snapcraft/10279/lib/python3.10/site-packages/craft_parts/executor/part_handler.py", line 493, in _run_step
2024-01-08 18:57:33.520 :: 2024-01-08 18:57:32.790     return step_handler.run_builtin()
2024-01-08 18:57:33.520 :: 2024-01-08 18:57:32.790   File "/snap/snapcraft/10279/lib/python3.10/site-packages/craft_parts/executor/step_handler.py", line 106, in run_builtin
2024-01-08 18:57:33.520 :: 2024-01-08 18:57:32.790     return handler()
2024-01-08 18:57:33.520 :: 2024-01-08 18:57:32.790   File "/snap/snapcraft/10279/lib/python3.10/site-packages/craft_parts/executor/step_handler.py", line 110, in _builtin_pull
2024-01-08 18:57:33.520 :: 2024-01-08 18:57:32.790     self._source_handler.pull()
2024-01-08 18:57:33.520 :: 2024-01-08 18:57:32.790   File "/snap/snapcraft/10279/lib/python3.10/site-packages/craft_parts/sources/git_source.py", line 305, in pull
2024-01-08 18:57:33.520 :: 2024-01-08 18:57:32.790     self._clone_new()
2024-01-08 18:57:33.520 :: 2024-01-08 18:57:32.790   File "/snap/snapcraft/10279/lib/python3.10/site-packages/craft_parts/sources/git_source.py", line 265, in _clone_new
2024-01-08 18:57:33.520 :: 2024-01-08 18:57:32.790     self._run(command + [str(self.part_src_dir)])
2024-01-08 18:57:33.520 :: 2024-01-08 18:57:32.790   File "/snap/snapcraft/10279/lib/python3.10/site-packages/craft_parts/sources/base.py", line 130, in _run
2024-01-08 18:57:33.520 :: 2024-01-08 18:57:32.790     raise errors.PullError(command=command, exit_code=err.returncode)
2024-01-08 18:57:33.520 :: 2024-01-08 18:57:32.790 craft_parts.sources.errors.PullError: Failed to pull source: command ['git', 'clone', '--recursive', '--branch', '0.24.0', 'https://github.com/extrawurst/gitui.git', '/root/parts/gitui/src'] exited with code 128.
2024-01-08 18:57:33.520 :: 2024-01-08 18:57:32.790 Make sure sources are correctly specified.
2024-01-08 18:57:33.520 Executing on host: lxc --project snapcraft config device show local:snapcraft-gitui-on-amd64-for-amd64-862
2024-01-08 18:57:33.573 Executing on host: lxc --project snapcraft config device remove local:snapcraft-gitui-on-amd64-for-amd64-862 disk-/root/project
2024-01-08 18:57:33.787 Executing on host: lxc --project snapcraft stop local:snapcraft-gitui-on-amd64-for-amd64-862
2024-01-08 18:57:37.920 Failed to execute pack in instance.
2024-01-08 18:57:37.923 Traceback (most recent call last):
2024-01-08 18:57:37.923   File "/snap/snapcraft/10279/lib/python3.10/site-packages/snapcraft/parts/lifecycle.py", line 469, in _run_in_provider
2024-01-08 18:57:37.923     instance.execute_run(cmd, check=True, cwd=output_dir)
2024-01-08 18:57:37.923   File "/snap/snapcraft/10279/lib/python3.10/site-packages/craft_providers/lxd/lxd_instance.py", line 293, in execute_run
2024-01-08 18:57:37.923     return self.lxc.exec(
2024-01-08 18:57:37.923   File "/snap/snapcraft/10279/lib/python3.10/site-packages/craft_providers/lxd/lxc.py", line 387, in exec
2024-01-08 18:57:37.923     return runner(final_cmd, timeout=timeout, check=check, **kwargs)
2024-01-08 18:57:37.923   File "/snap/snapcraft/10279/usr/lib/python3.10/subprocess.py", line 526, in run
2024-01-08 18:57:37.923     raise CalledProcessError(retcode, process.args,
2024-01-08 18:57:37.923 subprocess.CalledProcessError: Command '['lxc', '--project', 'snapcraft', 'exec', 'local:snapcraft-gitui-on-amd64-for-amd64-862', '--cwd', '/root/project', '--', 'env', 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin', 'SNAPCRAFT_MANAGED_MODE=1', 'snapcraft', 'pack', '--verbosity=brief', '--build-for', 'amd64']' returned non-zero exit status 1.
2024-01-08 18:57:37.923 Recommended resolution: Run the same command again with --debug to shell into the environment if you wish to introspect this failure.
2024-01-08 18:57:37.924 Full execution log: '/home/ubuntu/.local/state/snapcraft/log/snapcraft-20240108-185719.648564.log'
```

**Comment by sed-i** [comment]
I accidentally omitted a `v` in the version tag, so seems like snapcraft tried the branch after not finding the tag.
Would it be possible to add a log line for that? Currently it says
```
Cloning into '/root/parts/gitui/src'...
fatal: Remote branch 0.24.0 not found in upstream origin
Failed to pull source: command ['git', 'clone', '--recursive', '--branch', '0.24.0', 'https://github.com/extrawurst/gitui.git', '/root/parts/gitui/src'] exited with code 128.
Make sure sources are correctly specified.
```

It would be helpful if there was a log line such as
```
Tag not found, trying branch.
```

**Comment by mr-cal** [comment]
> seems like snapcraft tried the branch after not finding the tag

We don't have fallback logic for this ([source](https://github.com/canonical/craft-parts/blob/c5bf8edf35b0739081cd354c1c695496f5a4be2b/craft_parts/sources/git_source.py#L300)), because `git clone` will accept a branch or tag for `--branch`.

> It would be helpful if there was a log line such as

> > Tag not found, trying branch.

This is a good suggestion but I'm going to close this issue since Snapcraft doesn't do this.
