### ISSUE TITLE
 Fails to parse erroenous build output and freezes indefinitely 

### ISSUE THREAD

**Issue by ricotz** [snapcore/snapcraft#4515]
### Bug Description

There are libreoffice snap builds for amd64 [1] and arm64 which are stuck.

Afaict snapcraft crashed while parsing the build output.

[1] https://launchpad.net/~libreoffice/df-libreoffice/+snap/libreoffice-fresh/+build/2350372

Originally reported at https://bugs.launchpad.net/snapcraft/+bug/2046156

### To Reproduce

Seems running a build which outputs e.g. an erroneous utf8 encoded string. In case of libreoffice it is an error message where it seems a byte gets cut off.

### Environment

Runs on Launchpad

### snapcraft.yaml

```shell
https://git.launchpad.net/~libreoffice/+git/libreoffice-snap/tree/snapcraft.yaml?h=24.2
```

### Relevant log output

```shell
:: [build HPX] el/helpcontent2/source/text/simpress/guide
:: Entity: line 1: parser error : Opening and ending tag mismatch: switchinline line 1 and root
Exception in thread Thread-45:
Traceback (most recent call last):
  File "/snap/snapcraft/10279/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/snap/snapcraft/10279/lib/python3.10/site-packages/craft_cli/messages.py", line 285, in run
    self._run_posix()
  File "/snap/snapcraft/10279/lib/python3.10/site-packages/craft_cli/messages.py", line 257, in _run_posix
    self._write(data)
  File "/snap/snapcraft/10279/lib/python3.10/site-packages/craft_cli/messages.py", line 242, in _write
    unicode_line = useful_line.decode("utf8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 0: invalid start byte
```

### Additional context

The deb build output looks like this which I would expect the snap build to behave as well:

[build HPX] el/helpcontent2/source/text/sbasic/python
HELPFILES=/tmp/gbuild.SMwYPO && S=/<<PKGBUILDDIR>> && I=$S/instdir && W=$S/workdir && POFILES=/tmp/gbuild.i4kgRa && LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}"$I/program:$I/program" $W/LinkTarget/Executable/helpex -l el -mi ${HELPFILES} -m ${POFILES} -o $W/HelpTranslatePartTarget/el/helpcontent2/source/text/sbasic/python && rm -f ${POFILES} && touch /<<PKGBUILDDIR>>/workdir/HelpTranslatePartTarget/el/helpcontent2/source/text/sbasic/python/done && rm -f ${HELPFILES}
[build HPX] el/helpcontent2/source/text/sbasic/shared
Entity: line 1: parser error : Opening and ending tag mismatch: switchinline line 1 and root
�αζί και επιστρέφοντας το άθροισμά τους.</root>
                                                                               ^
Entity: line 1: parser error : Premature end of data in tag root line 1
�αζί και επιστρέφοντας το άθροισμά τους.</root>
                                                                               ^
HELPFILES=/tmp/gbuild.HZ8Z3B && S=/<<PKGBUILDDIR>> && I=$S/instdir && W=$S/workdir && POFILES=/tmp/gbuild.MFTIRb && LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}"$I/program:$I/program" $W/LinkTarget/Executable/helpex -l el -mi ${HELPFILES} -m ${POFILES} -o $W/HelpTranslatePartTarget/el/helpcontent2/source/text/sbasic/shared && rm -f ${POFILES} && touch /<<PKGBUILDDIR>>/workdir/HelpTranslatePartTarget/el/helpcontent2/source/text/sbasic/shared/done && rm -f ${HELPFILES}
[build HPX] el/helpcontent2/source/text/sbasic/shared/01

**Comment by ricotz** [comment]
Sorry no, but I guess the version hides behind the snapcraft build **10279**

**Comment by tigarmo** [comment]
Oh that'll do, that's Snapcraft 8.0.1

**Comment by tigarmo** [comment]
Just a note here on the "completeness" of this issue: I was able to reproduce & fix the decoding issue, but I could *not* reproduce the freezing behavior. Since the freezing seems to happen because of the error, and the error was fixed, this issue can be seen as resolved. @ricotz please report back if you still experience the freezing.
